services:
  - type: static
    name: asistego-front
    runtime: static
    buildCommand: npm install && ./node_modules/.bin/ng build --configuration production
    publish: dist/asistego-angular/browser
    routes:
      - type: rewrite
        source: /
        destination: /index.html
      - type: rewrite
        source: /(.*)
        destination: /index.html
